# PowerShell script to export SSIS environment variables to CSV
# Author: Generated by Kiro
# Date: $(Get-Date)

# Parameters
#param(
#    [string]$DeleteFile = "N",
#    [string]$FilePath = "C:\Users\58811.WMCDOMAIN\OneDrive - Renown Health\Documents\Work\Scripts\accounts.csv"
#)

$DeleteFile = "Y"
#$FilePath = "C:\Users\58811.WMCDOMAIN\OneDrive - Renown Health\Documents\Work\Scripts\accounts.csv"
$OutputPath = "G:\Databases\Staging\CMSAPI\Archive\accounts.csv"
$ServerName = "rhnv-edwdev.rhnv.hosted"

# Check if delete flag is used
if ($DeleteFile -eq "Y" -or $DeleteFile -eq "yes" -or $DeleteFile -eq "true") {
    if (Test-Path $FilePath) {
        try {
            Remove-Item $FilePath -Force
            Write-Host "File deleted successfully: $FilePath" -ForegroundColor Green
            exit 0
        } catch {
            Write-Error "Failed to delete file: $($_.Exception.Message)"
            exit 1
        }
    } else {
        Write-Host "File not found: $FilePath" -ForegroundColor Yellow
        exit 0
    }
}

# Connection parameters
#$ServerName = "RWN-SQLTW009"
$DatabaseName = "SSISDB"
$OutputPath = $FilePath

# SQL Query
$Query = @"
SELECT a.[variable_id]
      ,a.[environment_id]
      ,b.environment_name
      ,a.[name]
      ,COALESCE([value],CONVERT(nvarchar(4000),DECRYPTBYKEYAUTOCERT(CERT_ID(N'MS_Cert_Env_' + CONVERT(nvarchar(20), a.[environment_id])), NULL, a.[sensitive_value]))) AS DecryptedValue
FROM [SSISDB].[internal].[environment_variables] a
JOIN SSISDB.internal.environments b ON b.environment_id = a.environment_id
"@

try {
    Write-Host "Connecting to SQL Server: $ServerName" -ForegroundColor Green
    Write-Host "Database: $DatabaseName" -ForegroundColor Green
    
    # Import SQL Server module if available
    if (Get-Module -ListAvailable -Name SqlServer) {
        Import-Module SqlServer -ErrorAction SilentlyContinue
    }
    
    # Create connection string using Windows Authentication
    $ConnectionString = "Server=$ServerName;Database=$DatabaseName;Integrated Security=True;TrustServerCertificate=True;"
    
    # Execute query and get results
    Write-Host "Executing query..." -ForegroundColor Yellow
    
    $Connection = New-Object System.Data.SqlClient.SqlConnection($ConnectionString)
    $Command = New-Object System.Data.SqlClient.SqlCommand($Query, $Connection)
    $DataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter($Command)
    $DataTable = New-Object System.Data.DataTable
    
    $Connection.Open()
    $RecordsReturned = $DataAdapter.Fill($DataTable)
    $Connection.Close()
    
    Write-Host "Query executed successfully. Records returned: $RecordsReturned" -ForegroundColor Green
    
    # Ensure output directory exists
    $OutputDirectory = Split-Path $OutputPath -Parent
    if (!(Test-Path $OutputDirectory)) {
        New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
        Write-Host "Created directory: $OutputDirectory" -ForegroundColor Yellow
    }
    
    # Export to CSV
    Write-Host "Exporting data to CSV: $OutputPath" -ForegroundColor Yellow
    $DataTable | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
    
    Write-Host "Export completed successfully!" -ForegroundColor Green
    Write-Host "File saved to: $OutputPath" -ForegroundColor Cyan
    
    # Display summary
    Write-Host "`nSummary:" -ForegroundColor Magenta
    Write-Host "- Server: $ServerName" -ForegroundColor White
    Write-Host "- Database: $DatabaseName" -ForegroundColor White
    Write-Host "- Records exported: $RecordsReturned" -ForegroundColor White
    Write-Host "- Output file: $OutputPath" -ForegroundColor White
    
} catch {
    Write-Error "An error occurred: $($_.Exception.Message)"
    Write-Host "Error Details:" -ForegroundColor Red
    Write-Host $_.Exception.ToString() -ForegroundColor Red
    
    # Common troubleshooting suggestions
    Write-Host "`nTroubleshooting suggestions:" -ForegroundColor Yellow
    Write-Host "1. Verify SQL Server name and connectivity" -ForegroundColor White
    Write-Host "2. Ensure you have permissions to access SSISDB database" -ForegroundColor White
    Write-Host "3. Check if SqlServer PowerShell module is installed: Install-Module -Name SqlServer" -ForegroundColor White
    Write-Host "4. Verify the output directory path exists and is writable" -ForegroundColor White
} finally {
    # Clean up connections
    if ($Connection -and $Connection.State -eq 'Open') {
        $Connection.Close()
    }
}

# Usage Examples:
# To export data: .\SSIS-Environment-Variables-Export.ps1
# To delete the file: .\SSIS-Environment-Variables-Export.ps1 -DeleteFile "Y"
# Alternative delete options: .\SSIS-Environment-Variables-Export.ps1 -DeleteFile "yes" or -DeleteFile "true"
# To use custom file path: .\SSIS-Environment-Variables-Export.ps1 -FilePath "C:\Custom\Path\myfile.csv"
# To delete custom file: .\SSIS-Environment-Variables-Export.ps1 -DeleteFile "Y" -FilePath "C:\Custom\Path\myfile.csv"